### ISSUE TITLE
Inkex is now up to date on Pypi

### ISSUE THREAD

**Issue by ldevillez** [xyz2tex/svg2tikz#94]
Pypi is now updated on pypi and we should use this version instead of the current one on the gitlab (for easier installation purpose): https://pypi.org/project/inkex/

# TODO
- [x] Update `pyproject.toml`
- [x] Update CI files
- [x] Build and release new version

**Comment by ldevillez** [comment]
Release will be done later
